config/routes.rb
Ann::Application.routes.draw do
  root 'pages#index'

  get 'resume', to: 'pages#resume', as: :resume
  get 'contact', to: 'pages#contact', as: :contact
  get 'contact/success', to: 'pages#contact_success'
  get 'about', to: 'pages#about', as: :about
  get 'making-of-video', to: 'pages#bofvideo', as: :bofvideo
  get 'aau-audio', to: 'pages#aauaudio', as: :aauaudio
  get 'error', to: 'pages#error', as: :error

  get 'criticism', to: 'criticisms#index', as: :criticisms
  get 'criticism/:id', to: 'criticisms#show', as: :criticism, constraints: { id: /\d+/ }

  get 'jewelry(/:page)', to: 'jewelry#index', as: :jewelry, defaults: { page: 1 }

  get '/:gallery', to: 'galleries#index', as: :gallery
  get '/:gallery/statement', to: 'galleries#statement', as: :gallery_statement
  get '/:gallery/:id', to: 'galleries#show', as: :gallery_image, constraints: { id: /\d+/ }

  post '/ajax/gallery-loupe-notice', to: 'galleries#dismiss_loupe_notice', as: :dismiss_loupe_notice
end

app/models/criticism.rb
class Criticism
  include ActiveModel::Model

  attr_accessor :id, :citation, :summary, :title, :full, :sidebar
  attr_writer :images

  cattr_accessor :all

  def full?
    full.present?
  end

  def summary?
    summary.present?
  end

  def sidebar?
    sidebar.present?
  end

  def images
    @images ||= []
  end

  def self.find(id)
    all.find { |c| c.id == id } || raise(NotFound)
  end

  class NotFound < RuntimeError; end
end

app/controllers/criticisms_controller.rb
class CriticismsController < ApplicationController
  before_action :load_criticisms, only: :index
  before_action :load_criticism, only: :show

  rescue_from Criticism::NotFound, with: :not_found

  def index; end

  def show; end

  private

  def load_criticisms
    @criticisms = Criticism.all
  end

  def load_criticism
    @criticism = Criticism.find(params[:id].to_i)
  end
end

app/views/criticisms/index.html.erb
<h2>Selected Published Criticism</h2>

<% criticisms_with_summary = @criticisms.select(&:summary?) %>
<% criticisms_in_sidebar = @criticisms.select(&:sidebar?) %>

<div class="row">
  <div class="col-sm-<%= criticisms_in_sidebar.empty? ? 12 : 8 %>">
    <% criticisms_with_summary.each do |criticism| %>
      <blockquote>
        <%= raw anneify criticism.summary %>
        <footer><cite>
          <% if criticism.full? %>
            <%= link_to criticism.citation, criticism_path(criticism.id) %>
          <% else %>
            <%= criticism.citation %>
          <% end %>
        </cite></footer>
      </blockquote>
    <% end %>
  </div>

  <% unless criticisms_in_sidebar.empty? %>
    <div class="col-sm-4" id="pages-box">
      <h4>Click on magazine below for full essay</h4>
      <% criticisms_in_sidebar.each do |criticism| %>
        <div class="pages-image">
          <%= link_to image_tag(criticism.images.first), criticism_path(criticism.id) %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/criticisms/show.html.erb
<% if @criticism.title %>
  <h2><%= @criticism.title %></h2>
<% end %>

<% if @criticism.citation %>
  <p class="byline"><%= @criticism.citation %></p>
<% end %>

<div class="row">
  <div class="col-sm-8">
    <%= raw anneify @criticism.full %>
    <div id="back-watch"><%= link_to image_tag("watch_2_left.jpg"), criticisms_path %></div>
  </div>

  <% unless @criticism.images.empty? %>
    <div class="col-xs-4" id="pages-box">
      <% @criticism.images.each do |image| %>
        <div class="pages-image"><%= image_tag(image) %></div>
      <% end %>
    </div>
  <% end %>
</div>