config/routes.rb
Ann::Application.routes.draw do
  root 'pages#index'

  get 'resume', to: 'pages#resume', as: :resume
  get 'contact', to: 'pages#contact', as: :contact
  get 'contact/success', to: 'pages#contact_success'
  get 'about', to: 'pages#about', as: :about
  get 'making-of-video', to: 'pages#bofvideo', as: :bofvideo
  get 'aau-audio', to: 'pages#aauaudio', as: :aauaudio
  get 'error', to: 'pages#error', as: :error

  get 'criticism', to: 'criticisms#index', as: :criticisms
  get 'criticism/:id', to: 'criticisms#show', as: :criticism, constraints: { id: /\d+/ }

  get 'jewelry(/:page)', to: 'jewelry#index', as: :jewelry, defaults: { page: 1 }

  get '/:gallery', to: 'galleries#index', as: :gallery
  get '/:gallery/statement', to: 'galleries#statement', as: :gallery_statement
  get '/:gallery/:id', to: 'galleries#show', as: :gallery_image, constraints: { id: /\d+/ }

  post '/ajax/gallery-loupe-notice', to: 'galleries#dismiss_loupe_notice', as: :dismiss_loupe_notice
end

app/views/shared/_copyright.html.erb
<div class="copyright">All content &copy; <%= Time.now.year %><br />Anne Arden McDonald</div>

app/views/shared/_footer.html.erb
<div id="main-footer" class="navbar-fixed-bottom">
  <div id="main-footer-right" class="hidden-xs">
    <%= render 'shared/logo' %>
    <%= render 'shared/social' %>
  </div>
</div>

app/views/shared/_logo.html.erb
<h1 class="logo hidden-xs">
  <a href="/">Anne Arden McDonald</a>
</h1>

app/views/shared/_sidebar.html.erb
<% _front_page = front_page? %>

<% unless _front_page %><%= render 'shared/logo' %><% end %>

<ul class="navigation">
  <li>
    New Work:
    <ul>
      <li<% if t20x16_page? %> class="current"<% end %>>
        <a href="<%= gallery_path(:t20x16) %>">20x16 ins.</a>
      </li>
      <li<% if t24x20_page? %> class="current"<% end %>>
        <a href="<%= gallery_path(:t24x20) %>">24x20 ins.</a>
      </li>
      <li<% if t40x30_page? %> class="current"<% end %>>
        <a href="<%= gallery_path(:t40x30) %>">40x30 ins.</a>
      </li>
      <li<% if scrolls_page? %> class="current"<% end %>>
        <a href="<%= gallery_path(:scrolls) %>">Scrolls</a>
      </li>
    </ul>
  </li>

  <li<% if other_work_page? %> class="current"<% end %>>
    <a href="<%= gallery_path(:other_work) %>">Other Work</a>
  </li>

  <li<% if about_page? %> class="current"<% end %>>
    <a href="<%= about_path %>">About</a>
  </li>

  <li<% if contact_page? %> class="current"<% end %>>
    <a href="<%= contact_path %>">Contact</a>
  </li>
</ul>

<% unless _front_page %>
  <footer class="hidden-xs">
    <%= render 'shared/social' %>
    <%= render 'shared/copyright' %>
  </footer>
<% end %>

app/views/shared/_social.html.erb
<div class="social">
  <a href="https://www.facebook.com/Anne-Arden-McDonald-116579048353973/">
    <%= fa_icon('facebook-square', title: 'Facebook') %>
  </a>
  <a href="https://www.instagram.com/anneardenmcdonald/">
    <%= fa_icon('instagram', title: 'Instagram') %>
  </a>
</div>