config/routes.rb
Ann::Application.routes.draw do
  root 'pages#index'

  get 'resume', to: 'pages#resume', as: :resume
  get 'contact', to: 'pages#contact', as: :contact
  get 'contact/success', to: 'pages#contact_success'
  get 'about', to: 'pages#about', as: :about
  get 'making-of-video', to: 'pages#bofvideo', as: :bofvideo
  get 'aau-audio', to: 'pages#aauaudio', as: :aauaudio
  get 'error', to: 'pages#error', as: :error

  get 'criticism', to: 'criticisms#index', as: :criticisms
  get 'criticism/:id', to: 'criticisms#show', as: :criticism, constraints: { id: /\d+/ }

  get 'jewelry(/:page)', to: 'jewelry#index', as: :jewelry, defaults: { page: 1 }

  get '/:gallery', to: 'galleries#index', as: :gallery
  get '/:gallery/statement', to: 'galleries#statement', as: :gallery_statement
  get '/:gallery/:id', to: 'galleries#show', as: :gallery_image, constraints: { id: /\d+/ }

  post '/ajax/gallery-loupe-notice', to: 'galleries#dismiss_loupe_notice', as: :dismiss_loupe_notice
end

app/views/pages/aauaudio.html.erb
<div class="container-fluid" id="media-container">
  <div class="row" id="about-page-row">
    <audio controls autoplay style="width: 100%;">
      <source src="/media/interviewAudio.mp3" type="audio/mpeg" />
    </audio>
  </div>
 </div>

app/views/pages/about.html.erb
<div class="container-constrained">
  <div class="row">
    <div class="col-xs-12">
      <p><strong>Anne Arden McDonald</strong> (born 1966) is a Brooklyn based visual artist who grew up in Atlanta Georgia. From age 15 to 30 she made self portraits by building installations in abandoned interiors and performing privately for her camera in these spaces, publishing a book of this work in 2004. For 20 years, she was a private dealer for 13 Czech and Slovak photographers who do performances for the camera. She also has a large body of dreamy photographs shot with a Diana camera over several decades. More recently she has been using light and chemistry the way a painter or sculptor would to build images on photographic paper.</p>
      <p>McDonald’s work has been exhibited widely: in the past 30 years, she has had 44 solo exhibitions in 10 countries (about 230 total shows in 14 countries) and has been published in over 215 places in 20 countries, including in Aperture, European Photography, and Eyemazing Magazines. Her work is in the collections of the Brooklyn Museum, the Worchester Art Museum, the Houston MFA, the Denver At Museum, the Detroit Institute of Art and the Bibliothque Nationale in Paris. She was a Lapine Fellow at the Millay Colony, was given a grant of studio space from the Sharpe Foundation, and has been in residence at the Byrdcliffe colony from 2015-2017. She taught for 6 years at Parsons School of Design in New York, and has lectured about topics such as staged photography, self portraiture, Czech and Slovak photography, alternative photography, and her own work.</p>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col-xs-12">
      <div>
        <%= link_to 'Résumé', resume_path, class: 'highlighted-link' %>
        <%= link_to '(Download PDF)', '/media/resume.pdf', class: 'highlighted-link' %>
      </div>
      <div>
        <%= link_to 'Press', criticisms_path, class: 'highlighted-link' %>
      </div>
      <div>
        <%= link_to 'Czech and Slovak Site', 'http://www.czechslovakphotos.com/', class: 'highlighted-link' %>
      </div>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col-xs-12 col-md-6 gallery-item">
      <%= link_to image_tag('https://i.vimeocdn.com/video/984886199-11273ac83ce19f85eb26e7a14935e912e20e617da899c027fcc735c0e7d813db-d_295x166', class: 'img-responsive', border: 0), 'https://player.vimeo.com/video/473591181' %>
      Walk-through of solo exhibition,<br />
      Center for Photography at Woodstock, October 2020
    </div>

    <div class="col-xs-12 col-md-6 gallery-item">
      <%= link_to image_tag('annetv.png', class: 'img-responsive', border: 0), 'https://www.youtube.com/watch?v=SBo3O2b4ARo' %>
      TV spot--Caught in the Act: Art in Brooklyn
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 col-md-6 gallery-item">
      <%= link_to image_tag('00me by dragin web crop.jpg', class: 'img-responsive', border: 0), aauaudio_path %>
      Interview with Rachel Hubbard
    </div>

    <div class="col-xs-12 col-md-6 gallery-item">
      <%= link_to image_tag('making_of_fragility.png', class: 'img-responsive', border: 0), bofvideo_path %>
      Video of the making of Body of Fragility
    </div>
  </div>
</div>

app/views/pages/bofvideo.html.erb
<div class="container-fluid" id="media-container">
  <div class="row" id="about-page-row">
    <video controls autoplay style="display: block; margin: 0 auto;">
      <source src="/media/Body_of_Fragility-480x270.mp4" type="video/mp4" />
  </div>
</div>

app/views/pages/contact.html.erb
<div class="row">
  <div class="col-md-8">
    <p>
      For exhibition information, print purchases, and speaking or teaching engagements, please use the form below or contact me directly at <a href="mailto:Anne@AnneArdenMcDonald.com">Anne@AnneArdenMcDonald.com</a>.
    </p>

    <form method="POST" action="https://formspree.io/anne@anneardenmcdonald.com">
      <input type="text" name="_gotcha" style="display:none" />
      <input type="hidden" name="_next" value="<%= contact_success_url %>" />

      <div class="form-group">
        <label for="email">Your Email address</label>
        <input type="email" name="email" class="form-control" id="email" placeholder="Email">
      </div>

      <div class="form-group">
        <label for="message">Message</label>
        <textarea name="body" class="form-control" rows="3"></textarea>
      </div>

      <button type="submit" class="btn btn-default">Send</button>
    </form>
  </div>

  <div class="col-md-4">
    <%= image_tag('me and tree sm copy.jpg') %>
  </div>
</div>

app/views/pages/contact_success.html.erb
<div class="container-constrained">
  <div class="row">
    <div class="col-12">
      <p>Thank you for getting in touch.</p>
      <a href="/">&larr; Go back to the front page</a>
    </div>
  </div>
</div>

app/views/pages/error.html.erb
<div class="container-constrained">
  <div class="row">
    <div class="col-12">
      <p>The page you are looking for was not found.</p>
      <a href="/">&larr; Go back to the front page</a>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <%= image_tag('atom-planet.jpg', alt: 'atom-planet', class: 'img-responsive') %>
  </div>
</div>